In [2]:
import os

In [4]:
os.listdir()

['.849C9593-D756-4E56-8D6E-42412F2A707B',
 '.ipynb_checkpoints',
 '1. Gene editing and genome editing.docx',
 '1462437.pdf',
 '2. CAS9 Genome Engineering.docx',
 '2nd represilator.cps',
 '3. Synthetic Genomes.docx',
 'AbstractThe activation of T cells involves a complicated mec.docx',
 'Abstract\xa0\xa0The activation of T cells involves\xa0 a complicated.docx',
 'advanced biotech.xlsx',
 'Alternative Splicing - Part 1.docx',
 'Alternative Splicing - Part 2.docx',
 'Apps',
 'Attachments',
 'biotech data.xlsx',
 'Biotech exam.docx',
 'Biotech practical notes.docx',
 'BP tutoring programme.docx',
 'bradford assay.xlsx',
 'BT5014 Data handling report template- 2023-24 (AutoRecovered).docx',
 'BT5014 GFP results Octo 2024.xlsx',
 'BT5014.docx',
 'Buffer.docx',
 'CFTR mutations.docx',
 'Comparing and contrasting the use of primary cells with established.docx',
 'Computer Workshop instruction notes.docx',
 'Course Feedback for 2024-2025.xlsx',
 'desktop.ini',
 'DNA analysis presentation 1_com

In [6]:
os.path.exists("/")

True

In [8]:
help(os.path.exists)

Help on function exists in module genericpath:

exists(path)
    Test whether a path exists.  Returns False for broken symbolic links



In [10]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [12]:
import numpy as np #u can give it a nickname so you dont have to repeatedly write out the full form
import pandas as pd

In [20]:
myList = ["Mike", "Ellie", "Kim", "Luna"]
myList[0] # note that Python is a 0-based language

'Mike'

In [24]:
myList[1:3]
# note that index 3 is NOT included and the '1' index is the 2nd element because Python starts counting at 0!

['Ellie', 'Kim']

In [28]:
myList[:3]

['Mike', 'Ellie', 'Kim']

In [34]:
myList[0:3]

['Mike', 'Ellie', 'Kim']

In [36]:
myList[::2] # the first 2 indices are empty, which just defaults to the first and last

['Mike', 'Kim']

In [38]:
myList[::1]

['Mike', 'Ellie', 'Kim', 'Luna']

In [40]:
myList[::3]

['Mike', 'Luna']

In [42]:
myList[-1] # -ve sign tells to starts from the end, give us the last element of the list. here it starts from 1 not 0

'Luna'

In [44]:
myList[-2]

'Kim'

In [48]:
myList[-5]

IndexError: list index out of range

In [50]:
myList[::-1]

['Luna', 'Kim', 'Ellie', 'Mike']

In [54]:
myList[::]

['Mike', 'Ellie', 'Kim', 'Luna']

In [56]:
myList[::-2] # reverses but gives every 2nd element

['Luna', 'Ellie']

In [58]:
myList[0.42]

TypeError: list indices must be integers or slices, not float

In [65]:
import numpy as np
dna_seqs = ['ATGGGACTGCCCTTGATGCCTCACGTATCCAAAAGCGTATCATGGAGCACTCGGAAACGCACTATAGCAATACCAGACCGTGATATACAACCAGATCACTCTACGATTAAACGACTGCGCCGCCGTATTGCGCTGCTTATCCGAGAAGCAGTCCCTCGTGCGACGCAGCACCAAGAACAAGTCTCAGAGTACCTTTGGACGTATGACTTCAGGATCGAGTCGGCGGCTAGGTTCTATGGGGAGCTCCGTGATAGGTCATCTAGACAGGGTGTGTATTATTTGAGAGTAAAACGAAATCCTCCTCGCATGTACGGGTCAATGGAATTCCCGGTCAGA',
            'ATGGACACCTGGACATACTCCCAAGAGGCTGGAGCAGTGCCCCATTCCTCGGTGCCTCAAGTTCTGGGAATGTGCAATCCTCCGCGAGACATTCAAGGTTTCAGACCACGCGATCGGGTTAAGATACTATCTCAAGTACTTCTTTCGTGTAAGGCACCACTAGAATTGCTTACTTATCCAGGCGGACAAACTGCAATCCTATCTTCATGGGGGGTAGATTTACCATTTTGTAAGAATCTAGACGCACCACGTGGGCGTAGCGACAGGGAGACACAATGGAGCTGCATGATATGGCGGGATCCAAGATCCATGGCGAGCGCGTCATACTTTAGGTGC',
            'ATGGTGCGCACGATTGAGTTGGAATTAGTCCCCAGACTGGCGACCATTACATACACCCTCCACCTTCCACGTCGGTTCAGCACGGGGTGGTGTTTCTCTCCAACACGAGGCCCGGGCGAATTAGTATTGATAATGCCTGGGCAGACAGCACTGGCCCGGCAGGAGATACTGGGCGATGGAAGACGTGGGTTAAGGCACGTCGGTTCTCTAGGTTTTCTATACTGGGCACGGAAGTTAGGGGCTAAAGAGCAACATACCTCTCCGCTGTCGGTCGATAGTGAGTCTTGCATAGCGATTGCTAAGAGCCTAGTTAAGCATACTCGTAACCGCGCCGCG',
            'ATGCCTCCCGGTATCGCTGAGGCCCTAGCAAACGCACAGATCAACCAACTTGTGTCTAACGCCATGGGATCTGCCGCATTAGCTAACAATATTACGCCTATAACGCACGGCTTACCTTTCAAATGTGCTGACCAAGTGGCCTCGATACAATTAGGGACTACAGGGGATAGATGTGCAAGTTTGTTTCTATCAGCGCCGGTGATTCTACGACCGTGTAATCAGAGGGCAGCGAAGATGGATAAGGGGTTGACCAACATGCTCAGTAATGATCCAGGAGCCGGTTATGCCATGCGAATATGCATGTGCACAGTAGCCGGGAGAGCTTGTATTCGTATA',
            'ATGACCCCACGCGGACCGTCAGGAGAAATCCTCTCACGGGATCCCGTCACTGTAACGCTCAGGGTCTTACGGCAACTCGAATGCTGTCGAAAATGTGGCAGTCAATCTCTATACCGGGGTCCGAGCTTTTTACATGTAATTTTGCAAGAATTCTTATATAGCACGATGAGACACGTACCCGATCACTTCGCCCAGCATACACTGATTAATACCGTCTATGTGATGTATTTACTTAAGACTCTCGCAACACCCGTGGCTTGGCGAAGTCTATCTGCACTAGTCGGGTCAGCCGTGCGGCGCGCACACACATCAAAGTGGCCGCAGTTGAGCGCAGTG']

len(dna_seqs[0])
len(dna_seqs[1])
len(dna_seqs[4])

336

In [67]:
dna_dims = ( 5, 5, 336) # 5 by 5 is because 5 dna seq compared to the 5 dna seq
dna_array = np.ndarray((5, 5, 336)) # note

In [69]:
dna_array = np.ndarray((5, 5, 336))
dna_array # creates an empty array with information taht was already in the storage
#This array has random numbers in it because it is assigned to specific piece of memory, so takes on the values in that memory block. It is better practise, and therefore less accident prone, to create an all-zeros array.

array([[[1.44324542e-311, 1.44324483e-311, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
         0.00000000e+000, 0.00000000e+000, 0.000000

In [71]:
dna_array = np.zeros((5, 5, 336))
dna_array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [77]:
dna_array.shape # attribute used for arrays and data frames, tells how many rows and columns are in that
# dimension 1, dimension 2, dimension 3 --> basically 336 5x5 arrays stacked on top of each other

(5, 5, 336)

In [91]:
for idx1 in range(len(dna_seqs)):
    # loop 1 gets each seq
    # loop 2 gets the other seq to compare to.
    seq1 = dna_seqs[idx1]
    for idx2 in range(len(dna_seqs)):
        seq2 = dna_seqs[idx2]
        # assume the sequences are the same length
        for nt in range(len(seq1)):
            if seq1[nt] == seq2[nt]:
                dna_array[idx1, idx2, nt] = 1
            else:
                dna_array[idx1, idx2, nt] = 0 # we don't actually need this because the default value
                print(dna_array)
                break

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]]

 [[1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 1. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 0. 1.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 1. 0.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]]

 [[1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 0. 0. 0.]
  [1. 1. 1. ... 1. 1. 1.

In [99]:
dna_array[0, 0, :] # sequence 1 matches perfectly to itself

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [93]:
dna_array[1, 4, :] 

array([1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 1.

In [97]:
dna_array[2, 4, :] 

array([1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0.

In [103]:
np.sum(dna_array[2, 4, :])

84.0

In [105]:
np.sum(dna_array[2, 2, :])

336.0

In [107]:
np.sum(dna_array, 0)

array([[5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 1., 2., 1.],
       [5., 5., 5., ..., 2., 1., 2.],
       [5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 2., 2., 2.]])

In [109]:
np.sum(dna_array, 1)

array([[5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 1., 2., 1.],
       [5., 5., 5., ..., 2., 1., 2.],
       [5., 5., 5., ..., 2., 2., 2.],
       [5., 5., 5., ..., 2., 2., 2.]])

In [115]:
np.sum(dna_array, 2) # 3rd dimension is the best option to figure out which 2 sequences matches the closest, we can see that all 336 nt matches when the sequences are matched against each other
# ans to "Can you find the 2 sequences that have the closest match to each other?"

array([[336.,  90.,  98.,  85.,  94.],
       [ 90., 336.,  90.,  94.,  97.],
       [ 98.,  90., 336.,  94.,  84.],
       [ 85.,  94.,  94., 336.,  87.],
       [ 94.,  97.,  84.,  87., 336.]])

In [119]:
np.sum(dna_array [ :, : , 99], axis = 0) # How many sequences match at the first nucleotide, or the 100th

array([2., 2., 1., 2., 2.])

In [121]:
np.sum(dna_array [ :, : , 99], axis = 1)

array([2., 2., 1., 2., 2.])

In [125]:
np.sum(dna_array [ :, : , 99], axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [123]:
np.sum(dna_array [ :, : , 0], axis = 0)

array([5., 5., 5., 5., 5.])

In [127]:
import pandas as pd

In [131]:
phone_book = {"Names": ["Mike", "Daniel", "Ellie", "Heather"],
             "Office": ["6.17", "5.23", "3.20", "3.18"],
             "Department": ["Immunology", "Neuroscience", "Developmental Biology", "Immunology"]}
pb_df = pd.DataFrame(phone_book)
pb_df

Names Office             Department
0     Mike   6.17             Immunology
1   Daniel   5.23           Neuroscience
2    Ellie   3.20  Developmental Biology
3  Heather   3.18             Immunology

In [149]:
pb_df.set_index("Names", inplace=True)

KeyError: "None of ['Names'] are in the columns"

In [133]:
pb_df.shape

(4, 3)